/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import DTO.User;
import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Francisco
 */
public class StartMenuView extends javax.swing.JInternalFrame {

    public User loguser;

    /**
     * Creates new form StartMenuView
     */
    public StartMenuView(User user) {
        initComponents();
        loguser = user;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnCreateIssue = new javax.swing.JButton();
        btnManIssues = new javax.swing.JButton();
        btnManProjects = new javax.swing.JButton();
        btnManUsers = new javax.swing.JButton();
        btnManWorkflows = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();

        jLabel1.setText("System functions:");

        btnCreateIssue.setText("Create Issue");
        btnCreateIssue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateIssueActionPerformed(evt);
            }
        });

        btnManIssues.setText("Manage Issues");
        btnManIssues.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManIssuesActionPerformed(evt);
            }
        });

        btnManProjects.setText("Manage Projects");
        btnManProjects.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManProjectsActionPerformed(evt);
            }
        });

        btnManUsers.setText("Manage Users");
        btnManUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManUsersActionPerformed(evt);
            }
        });

        btnManWorkflows.setText("Manage Workflows");
        btnManWorkflows.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManWorkflowsActionPerformed(evt);
            }
        });

        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnManWorkflows, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnManUsers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnManProjects, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnManIssues, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCreateIssue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(143, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(btnCreateIssue)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnManIssues)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnManProjects)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnManUsers)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnManWorkflows)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLogout)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnManProjectsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManProjectsActionPerformed
        // TODO add your handling code here:
        if (loguser.getRole().getId() == 2) {
            JOptionPane.showMessageDialog(null, "You are not allowed to perform this action.");
        } else {
            ProjectManView pro = new ProjectManView(loguser);
            getParent().add(pro);
            pro.setVisible(true);
            try {
                pro.setMaximum(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(StartMenuView.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnManProjectsActionPerformed

    private void btnManUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManUsersActionPerformed
        // TODO add your handling code here:
        if (loguser.getRole().getId() != 1) {
            JOptionPane.showMessageDialog(null, "You are not allowed to perform this action.");
        } else {
            UserManView muv = new UserManView(loguser);
            getParent().add(muv);
            muv.setVisible(true);
            try {
                muv.setMaximum(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(StartMenuView.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnManUsersActionPerformed

    private void btnManWorkflowsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManWorkflowsActionPerformed
        // TODO add your handling code here:
        if (loguser.getRole().getId() == 2) {
            JOptionPane.showMessageDialog(null, "You are not allowed to perform this action.");
        } else {
            ManWorkflowsView mwv = new ManWorkflowsView(loguser);
            getParent().add(mwv);
            mwv.setVisible(true);
            try {
                mwv.setMaximum(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(StartMenuView.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnManWorkflowsActionPerformed

    private void btnCreateIssueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateIssueActionPerformed
        // TODO add your handling code here:
        IssueCreateView icv = new IssueCreateView(loguser);
        getParent().add(icv);
        icv.setVisible(true);
        try {
            icv.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(StartMenuView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnCreateIssueActionPerformed

    private void btnManIssuesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManIssuesActionPerformed
        // TODO add your handling code here:
        IssueManView imv = new IssueManView(loguser);
        getParent().add(imv);
        imv.setVisible(true);
        try {
            imv.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(StartMenuView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnManIssuesActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        LoginView login = new LoginView();
        getParent().add(login);
        login.setVisible(true);
        try {
            login.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(StartMenuView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnLogoutActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateIssue;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnManIssues;
    private javax.swing.JButton btnManProjects;
    private javax.swing.JButton btnManUsers;
    private javax.swing.JButton btnManWorkflows;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
