/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.StatusWorkflowController;
import DTO.Status;
import DTO.User;
import DTO.Workflow;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Francisco
 */
public class StatusWorkflowView extends javax.swing.JInternalFrame {

    public User loguser;
    public Workflow workflow;
    String col[] = {"Id", "Name", "Workflow"};
    DefaultTableModel tablemodel = new DefaultTableModel(col, 0);
    StatusWorkflowController swc = new StatusWorkflowController();

    /**
     * Creates new form StatusWorkflowView
     */
    public StatusWorkflowView(User user, Workflow p_workflow) {
        initComponents();
        loguser = user;
        workflow = p_workflow;
        this.fillTable();
        jTable1.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }

    private void fillTable() {
        if (swc.fetchStatus(workflow).size() > 0) {
            for (int i = 0; i < swc.fetchStatus(workflow).size(); i++) {
                String[] linea = {Integer.toString(swc.fetchStatus(workflow).get(i).getId()),
                    swc.fetchStatus(workflow).get(i).getName(),
                swc.fetchStatus(workflow).get(i).getWorkflow().getName()};
                tablemodel.addRow(linea);
            }
        }
    }

    private void reset() {
        tablemodel.setRowCount(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnAdd = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        jTable1.setModel(tablemodel);
        jScrollPane1.setViewportView(jTable1);

        btnAdd.setText("Add Status");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnBack.setText("Go back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnBack))
                .addContainerGap(79, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        if (loguser.getRole().getId() != 1) {
            JOptionPane.showMessageDialog(null, "You are not allowed to perform this action.");
        } else {        
        Workflow wf = new Workflow();
        wf = this.workflow;
        String name = JOptionPane.showInputDialog(null, "Please add the name of the status.");
        Status st = new Status();
        st.setName(name);
        st.setWorkflow(wf);
        if(swc.createStatus(st)){
            JOptionPane.showMessageDialog(null, "Successfully added to the workflow " + wf.getName());
            this.reset();
            this.fillTable();
        } else {
            JOptionPane.showMessageDialog(null, "There was a problem adding the status to the workflow ");
        }
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
